# Generated by Django 5.2.8 on 2025-11-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EclipseUser', '0002_rename_eclipseuser_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EclipseUser',
        ),
    ]
