# Generated by Django 5.2.8 on 2025-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EclipseUser', '0003_rename_user_eclipseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclipseuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=50, verbose_name='displayname'),
        ),
    ]
