# Generated by Django 5.2.8 on 2025-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EclipseUser', '0004_alter_eclipseuser_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclipseuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
