# Generated by Django 5.2.8 on 2025-12-07 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EclipseRoom', '0002_alter_roommessage_room_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='roomuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='забанен'),
        ),
        migrations.AddField(
            model_name='roomuser',
            name='role',
            field=models.CharField(choices=[('creator', 'cоздатель'), ('moderator', 'модератор'), ('user', 'пользователь')], default='user', max_length=20, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='roommessage',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='EclipseRoom.roomuser', verbose_name='отправитель'),
        ),
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('room', 'user')},
        ),
    ]
